services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./server:/usr/src/app
      - ./client:/usr/src/client # Mount the client folder at /usr/src/client
      - /usr/src/app/node_modules
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client:/usr/src/app # Mount the client folder at /usr/src/client
      - /usr/src/app/node_modules

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
